@baseURL = http://localhost:3040
@token = Bearer {{$dotenv JWT_TOKEN}}
###@baseURL = https://wom22-ammar.azurewebsites.net/


###Get all users visa and info
GET {{baseURL}}/bankaccounts/info
Authorization: {{token}}

###Get all bankaccounts
GET {{baseURL}}/bankaccounts
Authorization: {{token}}

### Make a new bankaccounts
POST  {{baseURL}}/bankaccounts/
Authorization: {{token}}
Content-Type: application/json

# {
#     "firstName": "AMMAR2",
#     "lastName": "MAN2",
#     "cardType": "VISA2",
#     "cardNumber": "44569042319219555",
#     "cardDate": "8/20282",
#     "cardCode": "2182",
#     "cardMoney" :"10012"
# }

# {
#   "maker": "63f4b8d612235fceceb28a4f",
#   "firstName": "AMMAR",
#   "lastName": "MAN",
#   "cardType": "VISA",
#   "cardNumber": "4556904231921977",
#   "cardDate": "7/2026",
#   "cardCode": "7/2026",
#   "_id": "63f5284e81beb12702fae526",
#   "createdAt": "2023-02-21T20:23:42.150Z",
#   "updatedAt": "2023-02-21T20:23:42.150Z",
#   "__v": 0
# }

