@baseURL = http://localhost:3040
@token = Bearer {{$dotenv JWT_TOKEN}}
//@baseURL = https://wom22-ammar.azurewebsites.net/


GET {{baseURL}}/


###
### 
GET {{baseURL}}/users
Authorization: {{token}}


###
### 
GET {{baseURL}}/users/info
Authorization: {{token}}


###
### MAKE NEW USER
POST  {{baseURL}}/users
Authorization: {{token}}
Content-Type: application/json

{
    "firstName": "Boss",
    "lastName": "Bob",
    "email": "Test@gmail.com",
    "password": "123456",
     "archived": true
}
###  "firstName": "Lolo",
#   ##  "lastName": "Bob",
#   ##  "email": "Bob@arcada.fi",
#   ##  "password": "Password123",
# ##     "archived": true

### LOGIN
POST  {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "Test@gmail.com",
    "password": "123456"
}
 ###"email": "Bob@arcada.fi",
  ###  "password": "Password123"

### "email": "ammar@arcada.fi",
###   "password": "Password123"

###
### Aktivera user true
PATCH {{baseURL}}/users/63f5fdb730321af49ba9aa26
Content-Type: application/json
Authorization: {{token}}

{
    "archived": true
}


###

### Radera user 
DELETE {{baseURL}}/users/63566bcfe4012dcc3c44f2f4
Authorization: {{token}}


###
### Modifiera userdata en ting
PUT {{baseURL}}/users/6332ead72092c8016c9b6a62
Content-Type: application/json
Authorization: {{token}}

{
    "email": "test@arcada.soumi"
}
